# Generated by Django 3.2.7 on 2021-10-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_data',
            new_name='AccountData',
        ),
    ]
