# Generated by Django 3.2.7 on 2021-10-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_rename_account_data_accountdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountData',
        ),
    ]
